name: Export cache

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'OP branch'
        required: true
        default: '24.10'
        type: string

permissions:
  contents: read

jobs:
  export_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Environment
        run: |
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          mkdir -p /workdir/DL
      - name: Cache ${{ inputs.branch }} DL dependencies
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: /workdir/DL
          key: Cache-DL-${{ inputs.branch }}-
          restore-keys: |
            Cache-DL-${{ inputs.branch }}-
      - name: Compress DL Cache
        run: |
          pushd /workdir/DL
          tar -I zstd -cf /workdir/DL.tzst * --owner=0 --group=0 --no-same-owner --no-same-permissions || echo "No files to compress"
          popd
      - name: Upload DL Cache artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: DL-${{ inputs.branch }}.tzst
          path: /workdir/DL.tzst
          retention-days: 1
